### ISSUE TITLE
Provide a way to specify a list of attributes to copy from a container image

### ISSUE THREAD

**Issue by nfachan** [meticulous-software/meticulous#90]
Discussing this with @bobbobbio, we came up with the following possible syntax. 
```toml
[[directives]]
package = "package1"
image = "docker:rust:latest"
include = ["layers", "working_directory", "environment"]

[[directives]]
package = "package1"
mounts = [ { fs_type = "tmp", mount_point = "/tmp" } ]
```
The idea is that a directive can be one of two (for now) types. The image type is new.
